### ISSUE TITLE
emojis removed with unidecode

### ISSUE THREAD

**Issue by cod3licious** [jfilter/clean-text#11]
In a cleantext install with unidecode, emojis are removed, while they are preserved without unidecode. As emojis are an important part of informal communication nowadays, I think they should always be preserved (or there should be an additional  parameter to specify this). Furthermore, this inconsistency should probably be documented somewhere...

**Comment by jfilter** [comment]
Set `to_ascii=False` to avoid transliteration.

There are a lot of inconsistencies between unidecode and Python's fallback. It's documented here: https://github.com/jfilter/clean-text#installation.

It makes sense that unidecode removes emojis since it transforms the text into ASCII. But I agree that there should be an option to keep emojis.
